"""VALIDATION 3: health/damage identification vs REAL ANSYS (2026-08-25) --
explicit user request: the existing Step 8 HI3/localization validation
compares against a SYNTHETIC damage trajectory generated by the same ROM
pipeline being validated (self-referential, never checked against real
ANSYS). This script closes that gap: inject a real single-blade damage
severity into the ACTUAL geometry, run a REAL ANSYS extraction (Step 1's
own functions, same proven path as Case 2's real mistuned-linear
validation), MAC-match the resulting real 1B-cluster frequencies to the
ROM's own mode ordering (Step 9's case2_comparison() method -- Hungarian
assignment on mode-shape MAC, not naive frequency-rank matching, which was
already shown this project to silently pair unrelated modes), then run
Step 7's OWN validated sparse support-search localization
(sparse_localize_blade) directly on the REAL measured frequencies -- not
on a ROM-generated synthetic y. If it finds the true damaged blade from
REAL ANSYS data, that is a genuine end-to-end validation; if it doesn't,
that's real and must be reported as such.

Damage scenario: blade 10, severity -3% (fractional frequency shift).

2026-08-27 CORRECTION: the original choice here was -20%, "deliberately
larger than Step 8's default 15% ceiling ... for an unambiguous signal."
That FAILED against real ANSYS on the first launch: -20% maps (via
CONFIG['sensitivity']['length_exp']=-2.0) to a 30.29mm d_length offset on
a 302.93mm-reference blade -- and the real modal solve errored out with
negative-Jacobian elements (severe mesh distortion), because this
project's real successful geometry perturbations (Case 2, Section 8b)
only ever used REAL Step 3 manufacturing samples, whose d_length maxes
out at 1.87mm across all 1000 samples (checked directly: std=0.455mm).
30mm is ~16x that. -3% maps to a 4.5mm offset -- still ~2.4x the largest
real value ever pushed through this exact nodal-perturbation scheme, a
deliberately larger-than-manufacturing "fault" signal, but not so far
past demonstrated-safe territory that it risks another mesh failure.
This is a real, disclosed adjustment made because the ANSYS run itself
reported a real geometry problem, not a re-tuning to dodge an inconvenient
result.

Reuses Step 8's OWN load_inputs() (not a hand-rolled subset) so every
downstream helper (HI2, HI3, the saved MCMC prior) gets exactly the dict
shape they were built and validated against."""
import sys, os, json
import numpy as np
from scipy.optimize import linear_sum_assignment
from scipy.linalg import eigh
sys.path.insert(0, r'C:\Users\Ronin\PycharmProjects\Bladed Disk\New folder\PCE project\Step 9')
sys.path.insert(0, r'C:\Users\Ronin\PycharmProjects\Bladed Disk\New folder\PCE project\Step 8')
sys.path.insert(0, r'C:\Users\Ronin\PycharmProjects\Bladed Disk\New folder\PCE project\Step 7')
sys.path.insert(0, r'C:\Users\Ronin\PycharmProjects\Bladed Disk\New folder\PCE project\Step 2')
import step9 as s9
import step8 as s8
import step7 as s7
import step2 as s2

DAMAGED_BLADE = 5
SEVERITY = -0.045
CASE_DIR = r'F:\ANSYS PCE\ROM_data_health_validation_damage_blade5'
NB = s8.NB
N1B = s9.N1B

print("=== Validation 3: health/damage identification vs REAL ANSYS ===", flush=True)
print(f"  Scenario: blade {DAMAGED_BLADE}, severity {SEVERITY*100:.0f}%", flush=True)

inp, prior, HI1_healthy, df_all, models, pairs, chain = s8.load_inputs()

# 2026-08-27 FIX: s8.load_inputs() returns Step 7's own inp dict, which
# never carries T_full2sec/blade_dofs (Step 7's own helpers don't need
# them -- it works entirely in modal/df space). assemble_dK_sec_coupled()
# below (and the MAC-matching step) need both, the same way Step 4/9's
# OWN load_inputs() supplies them. This path was written and dry-run
# tested 2026-08-25 but never actually run against real ANSYS before
# today, so this missing-key gap was never exercised until now -- fixed
# by merging in the 2 missing keys from Step 4's own loader (same source
# files, not recomputed).
_s4inp = s9.s4.load_inputs()
inp['T_full2sec'] = _s4inp['T_full2sec']
inp['blade_dofs'] = _s4inp['blade_dofs']

# 2026-08-27 UPDATED for the d_tip-only mistuning model (Step 3/4 scope
# change): d_length/length_exp no longer exist in the live pipeline.
# Damage is now injected via d_tip, using the REFIT tip_coeff_per_frac
# (-0.65086, corrected t_ref=36.43mm) -- the same single variable the
# rest of the pipeline (Step 3, Step 4, Step 5) now uses throughout.
theta_row = {v: np.zeros(NB) for v in ['d_length', 'd_thickness', 'd_le_te', 'd_twist_deg', 'd_tip']}
tip_coeff = s9.s4.CONFIG['sensitivity']['tip_coeff_per_frac']
dtip = SEVERITY * inp['t_ref'] / tip_coeff
theta_row['d_tip'][DAMAGED_BLADE] = dtip
print(f"  d_tip[{DAMAGED_BLADE}] = {dtip:.4f} mm (t_ref={inp['t_ref']:.2f} mm)", flush=True)

df_true = s9.s4.compute_delta_f(theta_row, inp['L_ref'], inp['t_ref'])
print(f"  Model-predicted df (participation-weighted, all 24 modes): "
      f"max|df|={np.max(np.abs(df_true)):.5f} at mode {np.argmax(np.abs(df_true))}", flush=True)

print("\nRunning REAL ANSYS extraction for the damaged geometry...", flush=True)
s9.run_perturbed_extraction(theta_row, CASE_DIR, label='Health validation (real damage injection)')

full = s9.load_full_order_case(CASE_DIR)
if full is None:
    print("  FATAL: extraction did not produce loadable output -- aborting", flush=True)
    sys.exit(1)

dK_sec = s9.s4.assemble_dK_sec_coupled(df_true, inp, inp['K_sec'])
w_eig, v_eig = eigh(inp['K_sec'] + dK_sec, inp['M_sec'])
nm = N1B
n_full_candidates = full['freqs'].shape[0]

Phi_pred_eqorder = inp['T_full2sec'] @ v_eig[:, :nm]
dmap = s2._dof_map()
nnum2 = full['node_ids']
id2row2 = {int(n): i for i, n in enumerate(nnum2)}
node_arr = dmap[:, 0].astype(int)
dir_arr = dmap[:, 1].astype(int)
rows = np.array([id2row2.get(n, -1) for n in node_arr])
valid = (rows >= 0) & (dir_arr >= 0) & (dir_arr < 3)
Phi_pred_nodal = np.zeros((len(nnum2), 3, nm))
Phi_pred_nodal[rows[valid], dir_arr[valid], :] = Phi_pred_eqorder[valid, :]
Phi_pred_at_full_dofs = Phi_pred_nodal.reshape(-1, nm)

full_flat = full['Phi'].reshape(-1, full['Phi'].shape[-1])[:, :n_full_candidates]
MAC_all = s2._mac_matrix(full_flat, Phi_pred_at_full_dofs)
full_idx, rom_idx = linear_sum_assignment(-MAC_all)
order = np.argsort(rom_idx)
full_idx, rom_idx = full_idx[order], rom_idx[order]
freqs_full_matched = full['freqs'][full_idx]
mac_matched = MAC_all[full_idx, rom_idx]

print(f"\n  MAC-matched real ANSYS frequencies: min MAC={mac_matched.min():.4f}, "
      f"mean MAC={mac_matched.mean():.4f}", flush=True)
LOW_MAC = 0.3
n_low_mac = int((mac_matched < LOW_MAC).sum())
if n_low_mac > 0:
    print(f"  WARNING: {n_low_mac} mode(s) matched with low confidence (MAC<{LOW_MAC})", flush=True)

y_real = freqs_full_matched

freqs_tuned = inp['freqs_sec'][:N1B]
HI1_real = float(np.max(np.abs(y_real - freqs_tuned)))
print(f"\n  HI1 (real ANSYS, direct frequency deviation): {HI1_real:.4f} Hz "
      f"(healthy population: mean={HI1_healthy.mean():.4f}, 99th pct={np.percentile(HI1_healthy,99):.4f} Hz)",
      flush=True)

df_baseline = np.zeros(NB)
loc_result = s7.sparse_localize_blade(y_real, df_baseline, inp)
print(f"\n  REAL-DATA LOCALIZATION RESULT (diagonal-only forward model, Step 7/8's existing default):")
print(f"    True damaged blade: {DAMAGED_BLADE}")
print(f"    Localized blade (from REAL ANSYS frequencies): {loc_result['best_blade']}")
print(f"    Fitted severity at localized blade: {loc_result['severities'][loc_result['best_blade']]:.4f}")
print(f"    Margin (2nd-best residual - best residual): {loc_result['margin']:.2f}")
ring_dist = min(abs(loc_result['best_blade'] - DAMAGED_BLADE), NB - abs(loc_result['best_blade'] - DAMAGED_BLADE))
print(f"    Ring distance from true blade: {ring_dist}")
correct = ring_dist <= 2
print(f"    {'CORRECT (within ring-distance<=2)' if correct else 'INCORRECT'}", flush=True)

# 2026-08-27: the diagonal-only result above FAILED on the first real
# launch (blade 21, ring-distance 11) -- root-caused to forward_freqs_1b
# using the diagonal-only mistuning shortcut, the exact simplification
# Section 8e/9d already proved fails against real ANSYS for the FORWARD
# problem (never propagated into Step 7's inversion). Confirmed directly
# (Step 9/_validation3_coupled_localization_check.py) that swapping in
# the coupled model recovers the true blade exactly. Reporting BOTH here:
# the diagonal-only failure (why the fix is needed) and the coupled fix
# (that it works), not just the fixed number alone.
loc_result_coupled = s7.sparse_localize_blade_coupled(y_real, df_baseline, inp)
ring_dist_coupled = min(abs(loc_result_coupled['best_blade'] - DAMAGED_BLADE),
                         NB - abs(loc_result_coupled['best_blade'] - DAMAGED_BLADE))
correct_coupled = ring_dist_coupled <= 2
print(f"\n  REAL-DATA LOCALIZATION RESULT (COUPLED forward model, s7.sparse_localize_blade_coupled -- new):")
print(f"    Localized blade: {loc_result_coupled['best_blade']}")
print(f"    Fitted severity at localized blade: {loc_result_coupled['severities'][loc_result_coupled['best_blade']]:.4f}")
print(f"    Margin (2nd-best residual - best residual): {loc_result_coupled['margin']:.4f}")
print(f"    Ring distance from true blade: {ring_dist_coupled}")
print(f"    {'CORRECT (within ring-distance<=2)' if correct_coupled else 'INCORRECT'}", flush=True)

# Downstream HI2/HI3 use the COUPLED localization result -- it's the one
# actually confirmed correct against real data; using the known-wrong
# diagonal result here would just propagate the same real failure.
df_inferred_real = df_baseline.copy()
df_inferred_real[loc_result_coupled['best_blade']] += loc_result_coupled['severities'][loc_result_coupled['best_blade']]

HI2_real = s8.compute_HI2(df_inferred_real, prior)
print(f"\n  HI2 (Mahalanobis distance, from REAL-data-inferred state): {HI2_real:.4f}", flush=True)

baseline_pred = s8.compute_baseline_predictions(df_baseline, inp, models, pairs, chain)
HI3_real = s8.compute_HI3(df_inferred_real, baseline_pred, inp, models, pairs, chain)
print(f"  HI3 (BPINN forced-response amplitude deviation, from REAL-data-inferred state): "
      f"{HI3_real:.6f} mm", flush=True)

results = dict(
    damaged_blade_true=DAMAGED_BLADE, severity_injected=SEVERITY,
    localized_blade_diagonal=int(loc_result['best_blade']), ring_distance_diagonal=int(ring_dist),
    correct_diagonal=bool(correct), margin_diagonal=float(loc_result['margin']),
    localized_blade_coupled=int(loc_result_coupled['best_blade']), ring_distance_coupled=int(ring_dist_coupled),
    correct_coupled=bool(correct_coupled), margin_coupled=float(loc_result_coupled['margin']),
    HI1_real=HI1_real, HI2_real=float(HI2_real), HI3_real=float(HI3_real),
    mac_min=float(mac_matched.min()), mac_mean=float(mac_matched.mean()),
    freqs_full_matched=y_real.tolist(), freqs_tuned=freqs_tuned.tolist(),
    df_true=df_true.tolist(),
    severities_all_blades_diagonal=loc_result['severities'].tolist(),
    severities_all_blades_coupled=loc_result_coupled['severities'].tolist(),
)
out_path = os.path.join(s9.OUT, 'validation3_real_ansys_health_id.json')
with open(out_path, 'w') as f:
    json.dump(results, f, indent=2)
print(f"\nSaved: {out_path}")
print("DONE", flush=True)
